// src/components/App.jsx
import React from "react";

import Header from "./moj/Header";
import PrimaryNavigation from "./moj/PrimaryNavigation";
import ChangePassword from "../pages/ChangePassword";
import { Footer } from "govuk-react-jsx";

const App = () => (
  <>
    <a href="#main-content" className="govuk-skip-link">
      Skip to main content
    </a>
    <Header
      serviceLabel={{ text: "Sirius User Management", href: "/" }}
      items={[
        {
          text: "Supervision",
          href: "#",
        },
        {
          text: "LPA",
          href: "#",
        },
        {
          text: "Logout",
          href: "#",
        },
      ]}
    ></Header>
    <PrimaryNavigation
      items={[
        {
          text: "Users",
          href: "/users",
        },
        {
          text: "Teams",
          href: "/teams",
        },
        {
          text: "My details",
          href: "/my-details",
        },
        {
          text: "Change password",
          href: "/change-password",
          active: true,
        },
      ]}
    ></PrimaryNavigation>
    <div class="govuk-width-container ">
      <main
        class="govuk-main-wrapper govuk-main-wrapper--auto-spacing"
        id="main-content"
        role="main"
      >
        <ChangePassword />
      </main>
    </div>
    <Footer></Footer>
  </>
);

export default App;

// app/src/App.vue
<template>
  <a href="#main-content" class="govuk-skip-link">Skip to main content</a>
  
  <div class="moj-primary-navigation">
    <div class="moj-primary-navigation__container">
      <div class="moj-primary-navigation__nav">
        <nav class="moj-primary-navigation" aria-label="Primary navigation">
          <ul class="moj-primary-navigation__list">
            <li class="moj-primary-navigation__item">
              <router-link class="moj-primary-navigation__link" to="/home">Users</router-link>
            </li>
            
            <li class="moj-primary-navigation__item">
              <router-link class="moj-primary-navigation__link" to="/teams">Teams</router-link>
            </li>
            
            <li class="moj-primary-navigation__item">
              <router-link class="moj-primary-navigation__link" to="/my-details">My details</router-link>
            </li>
            
            <li class="moj-primary-navigation__item">
              <router-link class="moj-primary-navigation__link" to="/change-password">Change password</router-link>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>

  <div class="govuk-width-container ">
    <main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
      <router-view />
    </main>
  </div>
</template>
